const fs = require('fs');
const headers = {
    'WorldGrid': '#pragma once\n#include "../data_both.h"\n#include "../data_host.h"\n\nnamespace u6o::server::state {\n    struct WorldGrid {\n        unsigned char btu6[1024][1024];\n        unsigned char btu60[256][256];\n        object* od[1024][2048];\n        unsigned char btflags[256];\n        unsigned char chunks[1024][8][8];\n        unsigned char u6wci2[8][8][16][8][3];\n        unsigned short u6wci[128][128];\n        unsigned char u60ci2[32][16][3];\n        unsigned short u60ci[32][32];\n        objentry ol[32768];\n        long oln;\n        object* oul[65536];\n        long ouln;\n        object* f_oul[65536];\n        long f_ouln;\n    };\n}\n',
    'ObjectPool': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct ObjectPool {\n        object objb[524228];\n        long objb_last;\n        unsigned long objb_free[524228];\n        long objb_free_last;\n    };\n}\n',
    'VlnkPool': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct VlnkPool {\n        void* vlnkb_lnk[65536];\n        unsigned long vlnkb_off[65536];\n        void* vlnkb_lnks[65536];\n        long vlnkb_last;\n        unsigned long vlnkb_free[65536];\n        long vlnkb_free_last;\n    };\n}\n',
    'ResurrectQueue': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct ResurrectQueue {\n        object* resu[65536];\n        object* resu_body[65536];\n        unsigned short resu_body_type[65536];\n        float resu_wait[65536];\n        player* resu_player[65536];\n        unsigned char resu_partymember[65536];\n        unsigned short resu_x[65536];\n        unsigned short resu_y[65536];\n        long nresu;\n    };\n}\n',
    'RespawnQueue': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct RespawnQueue {\n        object* respawn[1200];\n        unsigned short respawn_delay[1200];\n        long respawn_last;\n    };\n}\n',
    'MoongateState': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct MoongateState {\n        unsigned char showmoongates;\n        unsigned short moongatex[8];\n        unsigned short moongatey[8];\n        object* moongate[8][2];\n        unsigned char moonphase;\n    };\n}\n',
    'WindState': '#pragma once\nnamespace u6o::server::state {\n    struct WindState {\n        char windx;\n        char windy;\n        unsigned char windnew;\n    };\n}\n',
    'HouseSaves': '#pragma once\n#include "../data_host.h"\n\nnamespace u6o::server::state {\n    struct HouseSaves {\n        housesav_info housesav[256];\n    };\n}\n',
    'EconomyTables': '#pragma once\nnamespace u6o::server::state {\n    struct EconomyTables {\n        unsigned char economy_setup[1024][4];\n        long economy_limit[1024][4];\n        long economy_value[1024][4];\n        long economy_change[1024][4];\n    };\n}\n',
    'ScheduleTables': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct ScheduleTables {\n        schedule_i schedule[256][32];\n        schedule_i schedule2[1024][32];\n        long newschedule2;\n    };\n}\n',
    'NpcRegistry': '#pragma once\n#include "../data_both.h"\n#include "../data_host.h"\n\nnamespace u6o::server::state {\n    struct NpcRegistry {\n        unsigned long npci[256];\n        unsigned char* npcinf;\n        npcbin_i* npcbin;\n        unsigned short npcobj[256];\n        crtenum_struct crtenum[1073];\n        object* crtenum_pathok_castok[1024];\n        short crtenum_pathok_castok_i;\n        object* crtenum_pathok[1024];\n        short crtenum_pathok_i;\n        object* crtenum_castok[1024];\n        short crtenum_castok_i;\n    };\n}\n',
    'SfxBuffer': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct SfxBuffer {\n        unsigned char sfbuffersend;\n        float sfbufferwait;\n        unsigned long sfi[256][256];\n        sfxtype sf[65536];\n        unsigned long sf_playerid[65536];\n        long sfn;\n        unsigned long sfx_playerid[256];\n    };\n}\n',
    'WizardEyeState': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct WizardEyeState {\n        unsigned char wizardeyesi;\n        unsigned short wizardeyesx[256];\n        unsigned short wizardeyesy[256];\n        unsigned char wizardeyesi2;\n        unsigned char wizardeyesadded;\n        object* wizardeyesobj;\n    };\n}\n',
    'AutoSetupState': '#pragma once\nnamespace u6o::server::state {\n    struct AutoSetupState {\n        unsigned short autosetup;\n        bool autosetup_next;\n        unsigned short autosetup_counter;\n        bool autospell;\n    };\n}\n',
    'KeybTarget': '#pragma once\nnamespace u6o::server::state {\n    struct KeybTarget {\n        char ktar_x[768];\n        char ktar_y[768];\n        float ktar_xydis[768];\n    };\n}\n',
    'MoverNew': '#pragma once\nnamespace u6o::server::state {\n    struct MoverNew {\n        unsigned long MOVERNEW_GLOBALFLAGS;\n        unsigned char MOVERNEW_ERROR;\n        unsigned char mover_blood[1024];\n        unsigned short mover_body[1024];\n    };\n}\n',
    'ReviveLoopExit': '#pragma once\nnamespace u6o::server::state {\n    struct ReviveLoopExit {\n        unsigned long revive_infiniteloopexit_i;\n        unsigned long revive_infiniteloopexit_i2;\n        unsigned short revive_infiniteloopexit_i3;\n    };\n}\n',
    'MiscAccountLogin': '#pragma once\n#include "../data_both.h"\n#include "../define_host.h"\n#include "../mytxt.h"\n\nnamespace u6o::server::state {\n    struct MiscAccountLogin {\n        unsigned char save_buffer[::u6o::server::kSaveSlotLast + 1];\n        txt* save_username[::u6o::server::kSaveSlotLast + 1];\n        txt* save_password[::u6o::server::kSaveSlotLast + 1];\n        txt* save_name[::u6o::server::kSaveSlotLast + 1];\n        unsigned long save_exp[::u6o::server::kSaveSlotLast + 1];\n        unsigned long save_bytes[::u6o::server::kSaveSlotLast + 1];\n        unsigned char save_dump;\n        unsigned char login_dead_callback;\n        unsigned short save_version;\n        unsigned char encryptcode[65536];\n        unsigned char format_usernames;\n    };\n}\n',
    'MiscPlayerCreation': '#pragma once\n#include "../mytxt.h"\n\nnamespace u6o::server::state {\n    struct MiscPlayerCreation {\n        txt* tname;\n        txt* tusername;\n        txt* tuserpassword;\n        txt* tnewuserpassword;\n        unsigned char tcustomportrait_upload;\n        unsigned short tcustomportrait[3584];\n        unsigned long tnamecolour;\n        unsigned char tmale_female;\n        unsigned short tport;\n        unsigned short ttype;\n        unsigned char tcreatecharacter;\n    };\n}\n',
    'MiscServerIdentity': '#pragma once\n#include "../data_both.h"\n#include "../define_host.h"\n#include "../mytxt.h"\n\nnamespace u6o::server::state {\n    struct MiscServerIdentity {\n        txt* admins[::u6o::server::kAdminsMax];\n        txt* motd;\n        txt* inbritannia;\n        long inbritannia_totalplayers;\n        unsigned long U6ONEWID;\n        player* playerlist[1024];\n        long playerlist_last;\n        unsigned char party_ok[8];\n    };\n}\n',
    'MiscSpellsReagents': '#pragma once\nnamespace u6o::server::state {\n    struct MiscSpellsReagents {\n        unsigned char cast_spell;\n        unsigned char staff_cast_spell;\n        long CASTSPELL_SPELLTYPE;\n        unsigned long treagent[8];\n        unsigned long tspell[256];\n        bool spellattcrt;\n        unsigned char itemused;\n    };\n}\n',
    'MiscDoorsLevers': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct MiscDoorsLevers {\n        long doorclose_last;\n        float doorclose_wait[1024];\n        object* doorclose_obj[1024];\n        object* doorclose_obj2[1024];\n        unsigned short doorclose_oldtype[1024];\n        unsigned short doorclose_oldtype2[1024];\n        long leverchange_last;\n        float leverchange_wait[1024];\n        object* leverchange_obj[1024];\n        unsigned short leverchange_oldtype[1024];\n        object* portcullis[256][16];\n        object* lever[256][16];\n        object* efield[256][16];\n        object* eswitch[256][16];\n    };\n}\n',
    'MiscMapSpecific': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct MiscMapSpecific {\n        unsigned short orbx[5][5];\n        unsigned short orby[5][5];\n        object* nuggetsfix;\n    };\n}\n',
    'MiscObjectCreation': '#pragma once\n#include "../data_both.h"\n\nnamespace u6o::server::state {\n    struct MiscObjectCreation {\n        unsigned long objr_x;\n        unsigned long objr_y;\n        unsigned long ol_tag;\n        unsigned long ol_tag_prev;\n        object* newll;\n        unsigned long mycount;\n    };\n}\n'
};
fs.mkdirSync('src/server/state', { recursive: true });
for (const [name, content] of Object.entries(headers)) {
    fs.writeFileSync('src/server/state/' + name + '.h', content);
}
console.log('Generated ' + Object.keys(headers).length + ' header files in src/server/state/');
