apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-pv-cheap
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-cheap
  csi:
    driver: file.csi.azure.com
    volumeHandle: stultimasixonlinecheap#host
    volumeAttributes:
      server: stultimasixonlinecheap.file.core.windows.net
      shareName: host
    nodeStageSecretRef:
      name: azure-file-secret-cheap
      namespace: ultima-dev
