apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: stultimasixonline#host
    volumeAttributes:
      server: stultimasixonline.file.core.windows.net
      shareName: host
    nodeStageSecretRef:
      name: azure-file-secret
      namespace: ultima-dev
