apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file-pvc
  namespace: ultima-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 100Gi