apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-saves-pvc
  namespace: ultima-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-cheap
  resources:
    requests:
      storage: 100Gi

