apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-saves-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-cheap
  csi:
    driver: file.csi.azure.com
    volumeHandle: stultimasixonlinecheap#saves
    volumeAttributes:
      server: stultimasixonlinecheap.file.core.windows.net
      shareName: saves
    nodeStageSecretRef:
      name: azure-file-secret-cheap
      namespace: ultima-dev

