apiVersion: v1
kind: Secret
metadata:
  name: azure-file-secret
  namespace: ultima-dev
type: Opaque
stringData:
  azurestorageaccountname: stultimasixonline
  azurestorageaccountkey: "<YOUR_AZURE_STORAGE_ACCOUNT_KEY>"
